import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/header/Header'
import About from '../components/About'
import Faq from '../components/Faq'
import Footer from '../components/Footer'
import Mission from '../components/Mission'
import Services from '../components/Services'
import Stat from '../components/Stat'
import Testimonals from '../components/Testimonals'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Point_blank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header/>

      <Services/>

      <About />
      <Mission/>
      
      <Faq/>

      <Testimonals/>
      <Stat/>
      
      <Footer/>



    </div>
  )
}
